[package]
name = "vsp"
version = "0.1.0"
authors = ["Leryn"]
edition = "2018"
description = "A toy language compiler"
repository = "https://github.com/leryn1122/vsp"
readme = "README.md"
keywords = ["compiler"]
license = "MIT"

[dependencies]
hashbrown = "0.12.0"
regex = "1.5.5"
#url = "2.2.2"
